version: 2
jobs:
  build:
    docker:
      - image: drevops/ci-builder
        environment:
          GOSS_FILES_STRATEGY: cp
          DOCKER_VERSION: 19.03.5
    working_directory: /root/project
    steps:
      - checkout
      - run:
          name: Lint scripts
          command: shellcheck seed-db.sh
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            curl -L -o "/tmp/docker-${DOCKER_VERSION}.tgz" "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" \
            && tar -xz -C /tmp -f "/tmp/docker-${DOCKER_VERSION}.tgz" \
            && mv /tmp/docker/* /usr/bin \
            && docker --version
      - run:
          name: Install goss
          command: curl -fsSL https://goss.rocks/install | sh && goss --version
      - run:
          name: Run Goss tests
          command: |
            docker build -t gosstestorg/gosstestimage:goss-test-tag .
            GOSS_FILES_PATH=tests/dgoss dgoss run -i gosstestorg/gosstestimage:goss-test-tag
      - run:
          name: Run Bats tests
          command: bats tests/bats/data.bats --tap
      - run:
          name: Deploy image for feature branches
          command: |
            if [ "${CIRCLE_BRANCH:0:8}" = "feature/" ]; then
              export DST_DOCKER_TAG="$(echo ${CIRCLE_BRANCH} | sed 's/[^a-zA-Z0-9]/-/g')"
              docker build -t drevops/mariadb-drupal-data:${DST_DOCKER_TAG} .            
              echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin "${DOCKER_REGISTRY:-docker.io}"
              docker push "drevops/mariadb-drupal-data:${DST_DOCKER_TAG}"
            fi
