version: 2
jobs:
  build:
    docker:
      - image: drevops/ci-builder
        environment:
          GOSS_FILES_STRATEGY: cp
          DOCKER_VERSION: 19.03.5
    working_directory: /root/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker
          command: |
            curl -L -o "/tmp/docker-${DOCKER_VERSION}.tgz" "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" \
            && tar -xz -C /tmp -f "/tmp/docker-${DOCKER_VERSION}.tgz" \
            && mv /tmp/docker/* /usr/bin \
            && docker --version
      - run:
          name: Install goss
          command: curl -fsSL https://goss.rocks/install | sh && goss --version
      - run:
          name: Build image
          command: docker build -t drevops/mariadb-drupal-data:latest .
      - run:
          name: Run Goss tests
          command: GOSS_FILES_PATH=tests/dgoss dgoss run -i drevops/mariadb-drupal-data:latest
      - run:
          name: Run Bats tests
          command: bats tests/bats/data.bats --tap
